name: CI
on:
  pull_request:
  push:
    branches: [main]
jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6
      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '20.x'
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - run: pnpm install
      - run: cd backend && npx prisma generate
      - run: cd backend && pnpm lint
      - run: cd backend && pnpm test